# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1619, 904)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("QlineEdit {\n"
"rgb(144, 203, 255)\n"
"}")
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.positionSlider = QtWidgets.QSlider(self.centralwidget)
        self.positionSlider.setGeometry(QtCore.QRect(280, 720, 811, 22))
        self.positionSlider.setStyleSheet("")
        self.positionSlider.setMaximum(99)
        self.positionSlider.setSingleStep(10)
        self.positionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.positionSlider.setObjectName("positionSlider")
        self.play_push = QtWidgets.QPushButton(self.centralwidget)
        self.play_push.setGeometry(QtCore.QRect(330, 760, 75, 23))
        self.play_push.setObjectName("play_push")
        self.next_frame_push = QtWidgets.QPushButton(self.centralwidget)
        self.next_frame_push.setGeometry(QtCore.QRect(550, 760, 121, 23))
        self.next_frame_push.setObjectName("next_frame_push")
        self.prev_frame_push = QtWidgets.QPushButton(self.centralwidget)
        self.prev_frame_push.setGeometry(QtCore.QRect(424, 760, 121, 23))
        self.prev_frame_push.setObjectName("prev_frame_push")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(720, 750, 47, 13))
        self.label.setObjectName("label")
        self.videoWindow = QtWidgets.QGraphicsView(self.centralwidget)
        self.videoWindow.setGeometry(QtCore.QRect(230, 0, 1061, 271))
        self.videoWindow.setAutoFillBackground(True)
        self.videoWindow.setObjectName("videoWindow")
        self.spinBox_offset = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_offset.setGeometry(QtCore.QRect(710, 770, 61, 31))
        self.spinBox_offset.setMinimum(-100000)
        self.spinBox_offset.setMaximum(1000000)
        self.spinBox_offset.setSingleStep(10)
        self.spinBox_offset.setObjectName("spinBox_offset")
        self.graphicsView = GraphicsLayoutWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 280, 1591, 431))
        self.graphicsView.setAutoFillBackground(True)
        self.graphicsView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsView.setObjectName("graphicsView")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(1300, 40, 271, 31))
        self.lcdNumber.setSmallDecimalPoint(True)
        self.lcdNumber.setDigitCount(10)
        self.lcdNumber.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber.setObjectName("lcdNumber")
        self.fps_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        self.fps_spin_box.setGeometry(QtCore.QRect(790, 770, 51, 31))
        self.fps_spin_box.setMaximum(200)
        self.fps_spin_box.setObjectName("fps_spin_box")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(800, 750, 47, 13))
        self.label_2.setObjectName("label_2")
        self.y_axes_range = QtWidgets.QGroupBox(self.centralwidget)
        self.y_axes_range.setGeometry(QtCore.QRect(850, 750, 111, 51))
        self.y_axes_range.setObjectName("y_axes_range")
        self.spinBox_max = QtWidgets.QSpinBox(self.y_axes_range)
        self.spinBox_max.setGeometry(QtCore.QRect(60, 29, 35, 18))
        self.spinBox_max.setMinimum(-999999999)
        self.spinBox_max.setMaximum(999999999)
        self.spinBox_max.setObjectName("spinBox_max")
        self.label_4 = QtWidgets.QLabel(self.y_axes_range)
        self.label_4.setGeometry(QtCore.QRect(60, 10, 35, 13))
        self.label_4.setObjectName("label_4")
        self.spinBox_min = QtWidgets.QSpinBox(self.y_axes_range)
        self.spinBox_min.setGeometry(QtCore.QRect(10, 29, 35, 18))
        self.spinBox_min.setMinimum(-99999999)
        self.spinBox_min.setMaximum(999999999)
        self.spinBox_min.setSingleStep(1)
        self.spinBox_min.setProperty("value", 0)
        self.spinBox_min.setObjectName("spinBox_min")
        self.label_5 = QtWidgets.QLabel(self.y_axes_range)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 35, 13))
        self.label_5.setObjectName("label_5")
        self.spinBoxGoFrame = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxGoFrame.setGeometry(QtCore.QRect(960, 770, 81, 21))
        self.spinBoxGoFrame.setMinimum(1)
        self.spinBoxGoFrame.setMaximum(999999999)
        self.spinBoxGoFrame.setObjectName("spinBoxGoFrame")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(970, 750, 81, 21))
        self.label_3.setObjectName("label_3")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 221, 271))
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setObjectName("listWidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1080, 750, 61, 16))
        self.label_6.setObjectName("label_6")
        self.go_to_time_spin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.go_to_time_spin.setGeometry(QtCore.QRect(1070, 770, 61, 21))
        self.go_to_time_spin.setDecimals(3)
        self.go_to_time_spin.setMaximum(100000000.0)
        self.go_to_time_spin.setObjectName("go_to_time_spin")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1350, 10, 191, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1350, 160, 191, 21))
        self.label_8.setObjectName("label_8")
        self.lcdNumber_stim = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_stim.setGeometry(QtCore.QRect(1300, 180, 271, 31))
        self.lcdNumber_stim.setSmallDecimalPoint(True)
        self.lcdNumber_stim.setDigitCount(10)
        self.lcdNumber_stim.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber_stim.setObjectName("lcdNumber_stim")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(1350, 110, 151, 23))
        self.lcdNumber_2.setSmallDecimalPoint(True)
        self.lcdNumber_2.setDigitCount(6)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1380, 90, 91, 21))
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1619, 21))
        self.menubar.setObjectName("menubar")
        self.menuData_Visualizer = QtWidgets.QMenu(self.menubar)
        self.menuData_Visualizer.setObjectName("menuData_Visualizer")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuPreferences = QtWidgets.QMenu(self.menubar)
        self.menuPreferences.setObjectName("menuPreferences")
        self.menuNavigation_type = QtWidgets.QMenu(self.menuPreferences)
        self.menuNavigation_type.setObjectName("menuNavigation_type")
        self.menuDown_sampling_value = QtWidgets.QMenu(self.menuPreferences)
        self.menuDown_sampling_value.setObjectName("menuDown_sampling_value")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuSegmentation = QtWidgets.QMenu(self.menuTools)
        self.menuSegmentation.setObjectName("menuSegmentation")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Video = QtWidgets.QAction(MainWindow)
        self.actionLoad_Video.setObjectName("actionLoad_Video")
        self.actionLoad_data = QtWidgets.QAction(MainWindow)
        self.actionLoad_data.setObjectName("actionLoad_data")
        self.actionRaw_data = QtWidgets.QAction(MainWindow)
        self.actionRaw_data.setObjectName("actionRaw_data")
        self.actionPreprocessed_data = QtWidgets.QAction(MainWindow)
        self.actionPreprocessed_data.setObjectName("actionPreprocessed_data")
        self.actionICA = QtWidgets.QAction(MainWindow)
        self.actionICA.setObjectName("actionICA")
        self.actionFPS = QtWidgets.QAction(MainWindow)
        self.actionFPS.setObjectName("actionFPS")
        self.actionFrames = QtWidgets.QAction(MainWindow)
        self.actionFrames.setObjectName("actionFrames")
        self.actionTime_of_signal = QtWidgets.QAction(MainWindow)
        self.actionTime_of_signal.setObjectName("actionTime_of_signal")
        self.actionvalue = QtWidgets.QAction(MainWindow)
        self.actionvalue.setObjectName("actionvalue")
        self.actionauto = QtWidgets.QAction(MainWindow)
        self.actionauto.setObjectName("actionauto")
        self.actionRMS = QtWidgets.QAction(MainWindow)
        self.actionRMS.setObjectName("actionRMS")
        self.actionMaximum_number_of_elements = QtWidgets.QAction(MainWindow)
        self.actionMaximum_number_of_elements.setObjectName("actionMaximum_number_of_elements")
        self.actionSlice_navigator = QtWidgets.QAction(MainWindow)
        self.actionSlice_navigator.setObjectName("actionSlice_navigator")
        self.actionTag = QtWidgets.QAction(MainWindow)
        self.actionTag.setObjectName("actionTag")
        self.menuData_Visualizer.addAction(self.actionLoad_Video)
        self.menuData_Visualizer.addAction(self.actionLoad_data)
        self.menuView.addAction(self.actionRaw_data)
        self.menuView.addAction(self.actionPreprocessed_data)
        self.menuView.addAction(self.actionICA)
        self.menuView.addAction(self.actionRMS)
        self.menuNavigation_type.addAction(self.actionFrames)
        self.menuNavigation_type.addAction(self.actionTime_of_signal)
        self.menuDown_sampling_value.addAction(self.actionvalue)
        self.menuDown_sampling_value.addAction(self.actionauto)
        self.menuPreferences.addSeparator()
        self.menuPreferences.addAction(self.actionFPS)
        self.menuPreferences.addAction(self.menuNavigation_type.menuAction())
        self.menuPreferences.addAction(self.menuDown_sampling_value.menuAction())
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.menuSegmentation.menuAction())
        self.menuTools.addAction(self.actionSlice_navigator)
        self.menuTools.addAction(self.actionTag)
        self.menubar.addAction(self.menuData_Visualizer.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuPreferences.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.play_push.setText(_translate("MainWindow", "Play"))
        self.next_frame_push.setText(_translate("MainWindow", "Next frame"))
        self.prev_frame_push.setText(_translate("MainWindow", "Previous frame"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; vertical-align:super;\">Offset</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "FPS "))
        self.y_axes_range.setTitle(_translate("MainWindow", "Y axes range"))
        self.label_4.setText(_translate("MainWindow", "max"))
        self.label_5.setText(_translate("MainWindow", "min"))
        self.label_3.setText(_translate("MainWindow", "Go to frame"))
        self.label_6.setText(_translate("MainWindow", "Go to time"))
        self.label_7.setText(_translate("MainWindow", "Subject video (time/frame)"))
        self.label_8.setText(_translate("MainWindow", "Stimulus Video (Time/frame)"))
        self.label_9.setText(_translate("MainWindow", "Stimulus number"))
        self.menuData_Visualizer.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuPreferences.setTitle(_translate("MainWindow", "Preferences"))
        self.menuNavigation_type.setTitle(_translate("MainWindow", "Navigation type"))
        self.menuDown_sampling_value.setTitle(_translate("MainWindow", "Down sampling value"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuSegmentation.setTitle(_translate("MainWindow", "Segmentation "))
        self.actionLoad_Video.setText(_translate("MainWindow", "Load Video"))
        self.actionLoad_data.setText(_translate("MainWindow", "Load data"))
        self.actionRaw_data.setText(_translate("MainWindow", "Raw data"))
        self.actionPreprocessed_data.setText(_translate("MainWindow", "Preprocessed data"))
        self.actionICA.setText(_translate("MainWindow", "ICA "))
        self.actionFPS.setText(_translate("MainWindow", "FPS"))
        self.actionFrames.setText(_translate("MainWindow", "Video frames"))
        self.actionTime_of_signal.setText(_translate("MainWindow", "Time of signal"))
        self.actionvalue.setText(_translate("MainWindow", "Value"))
        self.actionauto.setText(_translate("MainWindow", "Auto"))
        self.actionRMS.setText(_translate("MainWindow", "RMS"))
        self.actionMaximum_number_of_elements.setText(_translate("MainWindow", "Maximum number of elements"))
        self.actionSlice_navigator.setText(_translate("MainWindow", "Slice navigator"))
        self.actionTag.setText(_translate("MainWindow", "Tag"))

from pyqtgraph import GraphicsLayoutWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

